# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "AsmResolver";
    version = "6.0.0-beta.1";
    hash = "sha256-ZW61z6Qmztdy2NaiqxvNcP5RWBIiIO6CWNnqYq0MwoA=";
  })
  (fetchNuGet {
    pname = "AsmResolver.DotNet";
    version = "6.0.0-beta.1";
    hash = "sha256-VoTiIr2/r2my6sg2AOEeiqz9vZhWtq5mGaW2Hx90Uo4=";
  })
  (fetchNuGet {
    pname = "AsmResolver.PE";
    version = "6.0.0-beta.1";
    hash = "sha256-tTU/flTxRJaC4gkmI/gctqIriGIMntkgTs51TqzcQlg=";
  })
  (fetchNuGet {
    pname = "AsmResolver.PE.File";
    version = "6.0.0-beta.1";
    hash = "sha256-hPuFrpcm2VMiYEirsL4kYmAhOzjwjNXUklIfYJEonLo=";
  })
  (fetchNuGet {
    pname = "System.CommandLine";
    version = "2.0.0-beta4.22272.1";
    hash = "sha256-zSO+CYnMH8deBHDI9DHhCPj79Ce3GOzHCyH1/TiHxcc=";
  })
]
