//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;

namespace PatchCil.Helpers;

#nullable enable

internal static class RuntimeIdentifiers
{
    public static ImmutableArray<string> All { get; } = ["android", "android-arm", "android-arm64", "android-x64", "android-x86", "browser", "browser-wasm", "freebsd", "freebsd-arm64", "freebsd-x64", "haiku", "haiku-x64", "illumos", "illumos-x64", "ios", "ios-arm", "ios-arm64", "ios-x64", "ios-x86", "iossimulator", "iossimulator-arm64", "iossimulator-x64", "iossimulator-x86", "linux", "linux-arm", "linux-arm64", "linux-armel", "linux-armv6", "linux-bionic", "linux-bionic-arm", "linux-bionic-arm64", "linux-bionic-x64", "linux-bionic-x86", "linux-loongarch64", "linux-mips64", "linux-musl", "linux-musl-arm", "linux-musl-arm64", "linux-musl-armel", "linux-musl-armv6", "linux-musl-ppc64le", "linux-musl-riscv64", "linux-musl-loongarch64", "linux-musl-s390x", "linux-musl-x64", "linux-musl-x86", "linux-ppc64le", "linux-riscv64", "linux-s390x", "linux-x64", "linux-x86", "maccatalyst", "maccatalyst-arm64", "maccatalyst-x64", "osx", "osx-arm64", "osx-x64", "solaris", "solaris-x64", "tvos", "tvos-arm64", "tvos-x64", "tvossimulator", "tvossimulator-arm64", "tvossimulator-x64", "unix", "unix-arm", "unix-arm64", "unix-armel", "unix-armv6", "unix-loongarch64", "unix-mips64", "unix-ppc64le", "unix-riscv64", "unix-s390x", "unix-x64", "unix-x86", "wasi", "wasi-wasm", "win", "win-arm", "win-arm64", "win-x64", "win-x86"];

    public static bool IsValid([NotNullWhen(true)] string? value)
    {
        return value is "android" or "android-arm" or "android-arm64" or "android-x64" or "android-x86" or "browser" or "browser-wasm" or "freebsd" or "freebsd-arm64" or "freebsd-x64" or "haiku" or "haiku-x64" or "illumos" or "illumos-x64" or "ios" or "ios-arm" or "ios-arm64" or "ios-x64" or "ios-x86" or "iossimulator" or "iossimulator-arm64" or "iossimulator-x64" or "iossimulator-x86" or "linux" or "linux-arm" or "linux-arm64" or "linux-armel" or "linux-armv6" or "linux-bionic" or "linux-bionic-arm" or "linux-bionic-arm64" or "linux-bionic-x64" or "linux-bionic-x86" or "linux-loongarch64" or "linux-mips64" or "linux-musl" or "linux-musl-arm" or "linux-musl-arm64" or "linux-musl-armel" or "linux-musl-armv6" or "linux-musl-ppc64le" or "linux-musl-riscv64" or "linux-musl-loongarch64" or "linux-musl-s390x" or "linux-musl-x64" or "linux-musl-x86" or "linux-ppc64le" or "linux-riscv64" or "linux-s390x" or "linux-x64" or "linux-x86" or "maccatalyst" or "maccatalyst-arm64" or "maccatalyst-x64" or "osx" or "osx-arm64" or "osx-x64" or "solaris" or "solaris-x64" or "tvos" or "tvos-arm64" or "tvos-x64" or "tvossimulator" or "tvossimulator-arm64" or "tvossimulator-x64" or "unix" or "unix-arm" or "unix-arm64" or "unix-armel" or "unix-armv6" or "unix-loongarch64" or "unix-mips64" or "unix-ppc64le" or "unix-riscv64" or "unix-s390x" or "unix-x64" or "unix-x86" or "wasi" or "wasi-wasm" or "win" or "win-arm" or "win-arm64" or "win-x64" or "win-x86";
    }

    public static bool IsWindows(string value) =>
        value is "win" or "win-arm" or "win-arm64" or "win-x64" or "win-x86";

    public static bool IsApple(string value) =>
        value is "ios" or "ios-arm" or "ios-arm64" or "ios-x64" or "ios-x86" or "iossimulator" or "iossimulator-arm64" or "iossimulator-x64" or "iossimulator-x86" or "maccatalyst" or "maccatalyst-arm64" or "maccatalyst-x64" or "osx" or "osx-arm64" or "osx-x64";

    public static bool IsUnix(string value) =>
        value is "android" or "android-arm" or "android-arm64" or "android-x64" or "android-x86" or "freebsd" or "freebsd-arm64" or "freebsd-x64" or "haiku" or "haiku-x64" or "illumos" or "illumos-x64" or "ios" or "ios-arm" or "ios-arm64" or "ios-x64" or "ios-x86" or "iossimulator" or "iossimulator-arm64" or "iossimulator-x64" or "iossimulator-x86" or "linux" or "linux-arm" or "linux-arm64" or "linux-armel" or "linux-armv6" or "linux-bionic" or "linux-bionic-arm" or "linux-bionic-arm64" or "linux-bionic-x64" or "linux-bionic-x86" or "linux-loongarch64" or "linux-mips64" or "linux-musl" or "linux-musl-arm" or "linux-musl-arm64" or "linux-musl-armel" or "linux-musl-armv6" or "linux-musl-ppc64le" or "linux-musl-riscv64" or "linux-musl-loongarch64" or "linux-musl-s390x" or "linux-musl-x64" or "linux-musl-x86" or "linux-ppc64le" or "linux-riscv64" or "linux-s390x" or "linux-x64" or "linux-x86" or "maccatalyst" or "maccatalyst-arm64" or "maccatalyst-x64" or "osx" or "osx-arm64" or "osx-x64" or "solaris" or "solaris-x64" or "tvos" or "tvos-arm64" or "tvos-x64" or "tvossimulator" or "tvossimulator-arm64" or "tvossimulator-x64" or "unix" or "unix-arm" or "unix-arm64" or "unix-armel" or "unix-armv6" or "unix-loongarch64" or "unix-mips64" or "unix-ppc64le" or "unix-riscv64" or "unix-s390x" or "unix-x64" or "unix-x86";

    public static string GetLibraryExtension(string value)
    {
        if (IsWindows(value))
        {
            return ".dll";
        }
        else if (IsApple(value))
        {
            return ".dylib";
        }
        else if (IsUnix(value))
        {
            return ".so";
        }
        else
        {
            return "";
        }
    }

    public static IEnumerable<string> EnumerateSelfAndDescendants(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        if (!IsValid(value))
        {
            throw new ArgumentException("Provided RID is not a valid RID.", nameof(value));
        }

        switch (value)
        {
            case "android":
                yield return "android";
                yield return "linux-bionic";
                yield return "linux";
                yield return "unix";
                yield return "any";
                break;
            case "android-arm":
                yield return "android-arm";
                yield return "android";
                yield return "linux-bionic-arm";
                yield return "linux-bionic";
                yield return "linux-arm";
                yield return "linux";
                yield return "unix-arm";
                yield return "unix";
                yield return "any";
                break;
            case "android-arm64":
                yield return "android-arm64";
                yield return "android";
                yield return "linux-bionic-arm64";
                yield return "linux-bionic";
                yield return "linux-arm64";
                yield return "linux";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "android-x64":
                yield return "android-x64";
                yield return "android";
                yield return "linux-bionic-x64";
                yield return "linux-bionic";
                yield return "linux-x64";
                yield return "linux";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "android-x86":
                yield return "android-x86";
                yield return "android";
                yield return "linux-bionic-x86";
                yield return "linux-bionic";
                yield return "linux-x86";
                yield return "linux";
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "browser":
                yield return "browser";
                yield return "any";
                break;
            case "browser-wasm":
                yield return "browser-wasm";
                yield return "browser";
                yield return "any";
                break;
            case "freebsd":
                yield return "freebsd";
                yield return "unix";
                yield return "any";
                break;
            case "freebsd-arm64":
                yield return "freebsd-arm64";
                yield return "freebsd";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "freebsd-x64":
                yield return "freebsd-x64";
                yield return "freebsd";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "haiku":
                yield return "haiku";
                yield return "unix";
                yield return "any";
                break;
            case "haiku-x64":
                yield return "haiku-x64";
                yield return "haiku";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "illumos":
                yield return "illumos";
                yield return "unix";
                yield return "any";
                break;
            case "illumos-x64":
                yield return "illumos-x64";
                yield return "illumos";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "ios":
                yield return "ios";
                yield return "unix";
                yield return "any";
                break;
            case "ios-arm":
                yield return "ios-arm";
                yield return "ios";
                yield return "unix-arm";
                yield return "unix";
                yield return "any";
                break;
            case "ios-arm64":
                yield return "ios-arm64";
                yield return "ios";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "ios-x64":
                yield return "ios-x64";
                yield return "ios";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "ios-x86":
                yield return "ios-x86";
                yield return "ios";
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "iossimulator":
                yield return "iossimulator";
                yield return "ios";
                yield return "unix";
                yield return "any";
                break;
            case "iossimulator-arm64":
                yield return "iossimulator-arm64";
                yield return "iossimulator";
                yield return "ios-arm64";
                yield return "ios";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "iossimulator-x64":
                yield return "iossimulator-x64";
                yield return "iossimulator";
                yield return "ios-x64";
                yield return "ios";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "iossimulator-x86":
                yield return "iossimulator-x86";
                yield return "iossimulator";
                yield return "ios-x86";
                yield return "ios";
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "linux":
                yield return "linux";
                yield return "unix";
                yield return "any";
                break;
            case "linux-arm":
                yield return "linux-arm";
                yield return "linux";
                yield return "unix-arm";
                yield return "unix";
                yield return "any";
                break;
            case "linux-arm64":
                yield return "linux-arm64";
                yield return "linux";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-armel":
                yield return "linux-armel";
                yield return "linux";
                yield return "unix-armel";
                yield return "unix";
                yield return "any";
                break;
            case "linux-armv6":
                yield return "linux-armv6";
                yield return "linux";
                yield return "unix-armv6";
                yield return "unix";
                yield return "any";
                break;
            case "linux-bionic":
                yield return "linux-bionic";
                yield return "linux";
                yield return "unix";
                yield return "any";
                break;
            case "linux-bionic-arm":
                yield return "linux-bionic-arm";
                yield return "linux-bionic";
                yield return "linux-arm";
                yield return "linux";
                yield return "unix-arm";
                yield return "unix";
                yield return "any";
                break;
            case "linux-bionic-arm64":
                yield return "linux-bionic-arm64";
                yield return "linux-bionic";
                yield return "linux-arm64";
                yield return "linux";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-bionic-x64":
                yield return "linux-bionic-x64";
                yield return "linux-bionic";
                yield return "linux-x64";
                yield return "linux";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-bionic-x86":
                yield return "linux-bionic-x86";
                yield return "linux-bionic";
                yield return "linux-x86";
                yield return "linux";
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "linux-loongarch64":
                yield return "linux-loongarch64";
                yield return "linux";
                yield return "unix-loongarch64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-mips64":
                yield return "linux-mips64";
                yield return "linux";
                yield return "unix-mips64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl":
                yield return "linux-musl";
                yield return "linux";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-arm":
                yield return "linux-musl-arm";
                yield return "linux-musl";
                yield return "linux-arm";
                yield return "linux";
                yield return "unix-arm";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-arm64":
                yield return "linux-musl-arm64";
                yield return "linux-musl";
                yield return "linux-arm64";
                yield return "linux";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-armel":
                yield return "linux-musl-armel";
                yield return "linux-musl";
                yield return "linux-armel";
                yield return "linux";
                yield return "unix-armel";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-armv6":
                yield return "linux-musl-armv6";
                yield return "linux-musl";
                yield return "linux-armv6";
                yield return "linux";
                yield return "unix-armv6";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-ppc64le":
                yield return "linux-musl-ppc64le";
                yield return "linux-musl";
                yield return "linux-ppc64le";
                yield return "linux";
                yield return "unix-ppc64le";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-riscv64":
                yield return "linux-musl-riscv64";
                yield return "linux-musl";
                yield return "linux-riscv64";
                yield return "linux";
                yield return "unix-riscv64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-loongarch64":
                yield return "linux-musl-loongarch64";
                yield return "linux-musl";
                yield return "linux-loongarch64";
                yield return "linux";
                yield return "unix-loongarch64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-s390x":
                yield return "linux-musl-s390x";
                yield return "linux-musl";
                yield return "linux-s390x";
                yield return "linux";
                yield return "unix-s390x";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-x64":
                yield return "linux-musl-x64";
                yield return "linux-musl";
                yield return "linux-x64";
                yield return "linux";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-musl-x86":
                yield return "linux-musl-x86";
                yield return "linux-musl";
                yield return "linux-x86";
                yield return "linux";
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "linux-ppc64le":
                yield return "linux-ppc64le";
                yield return "linux";
                yield return "unix-ppc64le";
                yield return "unix";
                yield return "any";
                break;
            case "linux-riscv64":
                yield return "linux-riscv64";
                yield return "linux";
                yield return "unix-riscv64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-s390x":
                yield return "linux-s390x";
                yield return "linux";
                yield return "unix-s390x";
                yield return "unix";
                yield return "any";
                break;
            case "linux-x64":
                yield return "linux-x64";
                yield return "linux";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "linux-x86":
                yield return "linux-x86";
                yield return "linux";
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "maccatalyst":
                yield return "maccatalyst";
                yield return "ios";
                yield return "unix";
                yield return "any";
                break;
            case "maccatalyst-arm64":
                yield return "maccatalyst-arm64";
                yield return "maccatalyst";
                yield return "ios-arm64";
                yield return "ios";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "maccatalyst-x64":
                yield return "maccatalyst-x64";
                yield return "maccatalyst";
                yield return "ios-x64";
                yield return "ios";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "osx":
                yield return "osx";
                yield return "unix";
                yield return "any";
                break;
            case "osx-arm64":
                yield return "osx-arm64";
                yield return "osx";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "osx-x64":
                yield return "osx-x64";
                yield return "osx";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "solaris":
                yield return "solaris";
                yield return "unix";
                yield return "any";
                break;
            case "solaris-x64":
                yield return "solaris-x64";
                yield return "solaris";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "tvos":
                yield return "tvos";
                yield return "unix";
                yield return "any";
                break;
            case "tvos-arm64":
                yield return "tvos-arm64";
                yield return "tvos";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "tvos-x64":
                yield return "tvos-x64";
                yield return "tvos";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "tvossimulator":
                yield return "tvossimulator";
                yield return "tvos";
                yield return "unix";
                yield return "any";
                break;
            case "tvossimulator-arm64":
                yield return "tvossimulator-arm64";
                yield return "tvossimulator";
                yield return "tvos-arm64";
                yield return "tvos";
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "tvossimulator-x64":
                yield return "tvossimulator-x64";
                yield return "tvossimulator";
                yield return "tvos-x64";
                yield return "tvos";
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "unix":
                yield return "unix";
                yield return "any";
                break;
            case "unix-arm":
                yield return "unix-arm";
                yield return "unix";
                yield return "any";
                break;
            case "unix-arm64":
                yield return "unix-arm64";
                yield return "unix";
                yield return "any";
                break;
            case "unix-armel":
                yield return "unix-armel";
                yield return "unix";
                yield return "any";
                break;
            case "unix-armv6":
                yield return "unix-armv6";
                yield return "unix";
                yield return "any";
                break;
            case "unix-loongarch64":
                yield return "unix-loongarch64";
                yield return "unix";
                yield return "any";
                break;
            case "unix-mips64":
                yield return "unix-mips64";
                yield return "unix";
                yield return "any";
                break;
            case "unix-ppc64le":
                yield return "unix-ppc64le";
                yield return "unix";
                yield return "any";
                break;
            case "unix-riscv64":
                yield return "unix-riscv64";
                yield return "unix";
                yield return "any";
                break;
            case "unix-s390x":
                yield return "unix-s390x";
                yield return "unix";
                yield return "any";
                break;
            case "unix-x64":
                yield return "unix-x64";
                yield return "unix";
                yield return "any";
                break;
            case "unix-x86":
                yield return "unix-x86";
                yield return "unix";
                yield return "any";
                break;
            case "wasi":
                yield return "wasi";
                yield return "any";
                break;
            case "wasi-wasm":
                yield return "wasi-wasm";
                yield return "wasi";
                yield return "any";
                break;
            case "win":
                yield return "win";
                yield return "any";
                break;
            case "win-arm":
                yield return "win-arm";
                yield return "win";
                yield return "any";
                break;
            case "win-arm64":
                yield return "win-arm64";
                yield return "win";
                yield return "any";
                break;
            case "win-x64":
                yield return "win-x64";
                yield return "win";
                yield return "any";
                break;
            case "win-x86":
                yield return "win-x86";
                yield return "win";
                yield return "any";
                break;
        }
    }
}
